# -*- mode: dockerfile -*-
FROM ruby:2.5.1-stretch

WORKDIR /potepanec

RUN apt-get update                                                                                                                      \
  && apt-get install                                                                                                                    \
    openssl                                                                                                                             \
  && curl -sL https://deb.nodesource.com/setup_14.x | bash -                                                                             \
  && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -                                                                  \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list                                      \
  && sh -c 'wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'                                         \
  && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'   \
  && wget https://dev.mysql.com/get/mysql-apt-config_0.8.10-1_all.deb                                                                   \
  && DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.10-1_all.deb                                                           \
  && apt-get update															\
  && apt-get remove -y															\
    libmariadbclient18															\
    libmariadbclient-dev-compat														\
    libmariadbclient-dev														\
  && apt-get install -y --allow-unauthenticated						   					                                                                  \
    libmysqlclient-dev                                                                                                                  \
    mysql-client                                                                                                                        \
    libxml2-dev                                                                                                                         \
    libxslt-dev                                                                                                                         \
    libc6-dev                                                                                                                           \
    nodejs                                                                                                                              \
    yarn                                                                                                                                \
    zip                                                                                                                                 \
    google-chrome-stable                                                                                                                \
  && gem install foreman                                                                                                                \
  && CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`                                                \
  && wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/                           \
  && unzip ~/chromedriver_linux64.zip -d ~/                                                                                             \
  && rm ~/chromedriver_linux64.zip                                                                                                      \
  && chown root:root ~/chromedriver                                                                                                     \
  && chmod 755 ~/chromedriver                                                                                                           \
  && mv ~/chromedriver /usr/bin/chromedriver                                                                                            \
  && apt-get clean

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
